//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooService
{
    using System;

    [Serializable]
    public partial class Attraction : ZooDataModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public int AttractionManagerID { get; set; }
        public int PlaceID { get; set; }

        [field: NonSerialized]
        public virtual Worker Worker { get; set; }
        [field: NonSerialized]
        public virtual Place Place { get; set; }

        public override void Assign(ZooDataModel model)
        {
            if (model is Attraction attraction)
            {
                Name = attraction.Name;
                Description = attraction.Description;
                AttractionManagerID = attraction.AttractionManagerID;
                PlaceID = attraction.PlaceID;
            }
        }
    }
}
