//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooService
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class BalanceType : ZooDataModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BalanceType()
        {
            this.CashBalances = new HashSet<CashBalance>();
        }
    
        public string Description { get; set; }

        [field: NonSerialized]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBalance> CashBalances { get; set; }

        public override void Assign(ZooDataModel model)
        {
            if (model is BalanceType balanceType)
                Description = balanceType.Description;
        }
    }
}
