//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooService
{
    using System;

    [Serializable]
    public partial class CashBalance : ZooDataModel
    {
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<decimal> Money { get; set; }
        public int BalanceTypeID { get; set; }
        public string DetailedDescription { get; set; }

        [field: NonSerialized]
        public virtual BalanceType BalanceType { get; set; }

        public override void Assign(ZooDataModel model)
        {
            if (model is CashBalance cashBalance)
            {
                SubmitDate = cashBalance.SubmitDate;
                Money = cashBalance.Money;
                BalanceTypeID = cashBalance.BalanceTypeID;
                DetailedDescription = cashBalance.DetailedDescription;
            }
        }
    }
}
