//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooService
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Food : ZooDataModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.Animals = new HashSet<Animal>();
        }
    
        public string Name { get; set; }
        public Nullable<double> Amount { get; set; }

        [field: NonSerialized]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals { get; set; }

        public override void Assign(ZooDataModel model)
        {
            if (model is Food food)
            {
                Name = food.Name;
                Amount = food.Amount;
            }
        }
    }
}
