//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooService
{
    using System;

    [Serializable]
    public partial class Overtime : ZooDataModel
    {
        public System.DateTime Date { get; set; }
        public int Hours { get; set; }
        public int PaymentPercentage { get; set; }
        public int WorkerID { get; set; }

        [field: NonSerialized]
        public virtual Worker Worker { get; set; }

        public void SetPercentage()
        {
            if (Date.DayOfWeek == DayOfWeek.Saturday)
                PaymentPercentage = 250;
            else if (Date.DayOfWeek == DayOfWeek.Sunday)
                PaymentPercentage = 300;
            else
                PaymentPercentage = 150;
        }

        public override void Assign(ZooDataModel model)
        {
            if (model is Overtime overtime)
            {
                Date = overtime.Date;
                Hours = overtime.Hours;
                WorkerID = overtime.WorkerID;
                SetPercentage();
            }
        }
    }
}
