//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooService
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Place : ZooDataModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Place()
        {
            this.Animals = new HashSet<Animal>();
            this.Attractions = new HashSet<Attraction>();
            this.Workers = new HashSet<Worker>();
        }

        public string Name { get; set; }
        public Nullable<System.TimeSpan> OpenTime { get; set; }
        public Nullable<System.TimeSpan> CloseTime { get; set; }
        public Nullable<decimal> MaintenanceCost { get; set; }

        [field: NonSerialized]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals { get; set; }
        [field: NonSerialized]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attraction> Attractions { get; set; }
        [field: NonSerialized]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worker> Workers { get; set; }

        public override void Assign(ZooDataModel model)
        {
            if (model is Place place)
            {
                Name = place.Name;
                OpenTime = place.OpenTime;
                CloseTime = place.CloseTime;
                MaintenanceCost = place.MaintenanceCost;
            }
        }
    }
}
