//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooService
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Worker : ZooDataModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Attractions = new HashSet<Attraction>();
            this.Overtimes = new HashSet<Overtime>();
        }
    
        public string Surname { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public int PlaceID { get; set; }

        [field: NonSerialized]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attraction> Attractions { get; set; }
        [field: NonSerialized]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Overtime> Overtimes { get; set; }
        [field: NonSerialized]
        public virtual Place Place { get; set; }

        public override void Assign(ZooDataModel model)
        {
            if (model is Worker worker)
            {
                Surname = worker.Surname;
                Name = worker.Name;
                Age = worker.Age;
                Salary = worker.Salary;
                StartDate = worker.StartDate;
                PlaceID = worker.PlaceID;
            }
        }
    }
}
