//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooService
{
    [System.Serializable]
    public abstract class ZooDataModel
    {
        public int ID { get; set; }

        public abstract void Assign(ZooDataModel model);
    }
}